# Generated by Django 2.1.5 on 2019-02-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_procedure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='provider',
        ),
        migrations.AddField(
            model_name='procedure',
            name='provider',
            field=models.ManyToManyField(to='api.Provider'),
        ),
    ]
