# Generated by Django 2.1.5 on 2019-02-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
