# Generated by Django 2.1.5 on 2019-02-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190204_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
